### ISSUE TITLE
Typo in readme

### ISSUE THREAD

**Issue by loopDelicious** [postmanlabs/pmquickstarts#59]
The screenshot image in the README appears to contradict the README instructions to use hyphens in the module name.
<img width="790" alt="Screenshot 2023-11-02 at 1 56 23 PM" src="https://github.com/postmanlabs/pmquickstarts/assets/17693714/97edb6d3-46f6-4251-bc9d-e32fd453d96b">

**Comment by LKoech** [comment]
Hey I'd like to be assigned this issue. I made the correction would like you to review to see if it's okay.

**Comment by Muhammad-Owais-Warsi** [comment]
Hey, I really want to contribute to this. Can  you please assign this to me?

**Comment by loopDelicious** [comment]
Closed by #61
